FROM node:8-alpine
LABEL maintainer="Andrew Kopylov <aa74ko@gmail.com>"

RUN apk add --no-cache curl

WORKDIR /app

COPY ./src/ /app/
RUN npm install

ENV USER_ID=1000
RUN chown -R $USER_ID:$USER_ID /app
USER $USER_ID:$USER_ID

EXPOSE 3000

HEALTHCHECK --interval=5s --timeout=3s \
  CMD curl -f http://localhost:3000/status || exit 1

CMD "/app/run.sh"
